#!/bin/bash

set -u


find . -depth 1 -type d | while read dir; do
    package="${dir##*/}"
    echo "*** $package ***"
    echo

    find "$dir" -mindepth 1 | while read item; do
	if [[ ! -h "$item" && -d "$item" ]]; then
	    if [[ -z $(ls -A "$item") ]]; then
		echo "ERROR: empty directory: \"$item\""
	    fi
	    continue
	fi

	path="${item#*/*/}"

	if [[ -h "$item" ]]; then
	    if [[ $(readlink "$item") != "/${path}" ]]; then
		echo "ERROR: bad symlink: \"$item\""
		continue
	    else
		path="@${path}"
	    fi
	else
	    if [[ "${path}" == */.empty ]]; then
		path="${path%/*}"
	    fi
	    path=" ${path}"
	fi

	echo "$path"
    done

    echo
done
